export const TEXT_CONFIG = {
  metadata: {
    title: 'Nexara - AI Research Agent',
    description:
      'Autonomous deep research with citations. Ask any research question and get a comprehensive, well-sourced report.',
  },

  appShell: {
    openMenuAriaLabel: 'Open menu',
  },

  sidebar: {
    nav: {
      newResearch: 'New Research',
      history: 'History',
      projects: 'Projects',
      settings: 'Settings',
    },
    searchRuns: 'Search Runs',
    filterRunsPlaceholder: 'Filter runs...',
    noRunsFound: 'No runs found',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    collapse: 'Collapse',
    closeMenuAriaLabel: 'Close menu',
  },

  home: {
    brandName: 'Nexara',
    brandDescription:
      'Your AI-powered autonomous research agent - searches the web, builds knowledge graphs, verifies claims, and delivers comprehensive reports.',
    startingStatus: 'Starting research...',
    researchingStatus: 'Currently researching your query...',
    startFailed: 'Failed to start research. Please try again.',
    activeSessionTitle: 'Current research session',
    activeSessionSubtitle:
      'Live progress continues here while you can steer with new context from the chatbox.',
    openRun: 'Open detailed view',
    traceTitle: 'Agent Trace',
    features: [
      {
        title: 'Parallel Research',
        desc: 'Multiple search workers run simultaneously',
      },
      {
        title: 'Knowledge Graph',
        desc: 'Auto-builds entity relationships',
      },
      {
        title: 'Verified Claims',
        desc: 'CoVe pipeline fact-checks every claim',
      },
      {
        title: 'Academic + Web',
        desc: 'Searches papers, journals, and the web',
      },
    ],
  },

  researchInput: {
    depthQuick: 'Quick',
    depthStandard: 'Standard',
    depthDeep: 'Deep',
    model70b: 'Llama 70B',
    model8b: 'Llama 8B',
    placeholderDefault: 'What would you like to research?',
    placeholderListening: 'Listening...',
    placeholderTranscribing: 'Transcribing...',
    transcribingStatus: 'Transcribing...',
    recordingStatus: 'REC',
    addUrlPlaceholder: 'https://example.com',
    addButton: 'Add',
    attachFilesTitle: 'Attach files',
    addUrlTitle: 'Add URL',
    researchModeTitle: 'Research mode',
    modelTitle: 'Model',
    submitStarting: 'Starting...',
    submitDefault: 'Research',
    voiceTitleStart: 'Voice dictation',
    voiceTitleStop: 'Stop recording',
    keyboardHintPrefix: 'Press',
    keyboardHintSuffix: 'to submit',
    steeredUserLabel: 'You',
  },

  runPage: {
    status: {
      queued: 'Queued',
      researching: 'Researching',
      completed: 'Completed',
      failed: 'Failed',
    },
    loadingResearch: 'Loading research...',
    loadFailed: 'Failed to load run data.',
    backTitle: 'Back',
    noQueryFallback: 'Research Run',
    traceTitle: 'Agent Trace',
    traceToggle: 'Trace',
    eventsTrackedSuffix: 'tracked',
    iterationPrefix: 'Iteration',
    runFailedDefault: 'Run failed. Check Agent Trace for details.',
    assistantName: 'Nexara',
    userLabel: 'You',
    steeringUserLabel: 'You - Steering',
    steeringPlaceholder: 'Add extra context while research continues...',
    steeringHint:
      'Add guidance without interrupting the current run. The agent applies it at the next reasoning checkpoint.',
    steeringQueuedSuccess: 'Queued. It will be used in the next reasoning step.',
    steeringQueuedFailure: 'Failed to queue steering context.',
    steeringSubmitTitle: 'Queue steering input',
    thinkingSubtitle: 'Nexara is working on your query',
    thinkingInit: 'Initializing research...',
    thinkingSteps: ['Planning', 'Searching', 'Analyzing', 'Synthesizing'],
    steeringQueuedEventMessage: 'User added steering context',
    steeringAppliedMessage: 'User steering context has been applied',
  },

  traceTimeline: {
    waitingForEvents: 'Waiting for live events...',
    routeQuickChat: 'Quick chat response - no research needed',
    routeDirectAnswer: 'Direct answer - no deep research needed',
    routeLightLookup: 'Light lookup mode',
    routeFullResearch: 'Starting full research pipeline',
    routeClassifying: 'Classifying query...',
    planCreatedPrefix: 'Created',
    planCreatedSuffix: 'research sub-questions',
    searchFoundPrefix: 'Found',
    searchFoundSuffix: 'search results',
    fetchedPrefix: 'Fetched',
    fetchedSuffix: 'pages',
    indexedPrefix: 'Indexed',
    indexedSuffix: 'content chunks',
    retrievedPrefix: 'Retrieved',
    retrievedSuffix: 'evidence pieces',
    reportWrittenPrefix: 'Report written',
    reportWriting: 'Writing research report...',
    reportPassed: 'Report passed quality checks',
    reportNeedsRefine: 'Report needs refinement',
    refiningReport: 'Refining report based on evaluation feedback',
    researchComplete: 'Research complete!',
    pdfGenerated: 'PDF report generated',
    steeringQueued: 'User added extra context for next reasoning step',
    steeringAppliedPrefix: 'Applied',
    steeringAppliedSuffix: 'queued steering update(s)',
    steeringAppliedGeneric: 'Queued steering context has been applied',
    defaultError: 'An error occurred',
  },

  reportViewer: {
    runningMessage: 'Researching and writing report...',
    noReport: 'No report available yet.',
    pdfDownloadFailed: 'PDF download failed. The report may still be generating.',
    generatingPdf: 'Generating PDF...',
    downloadPdf: 'Download PDF',
    qualityScores: 'Quality Scores',
    scoreCoverage: 'Coverage',
    scoreAccuracy: 'Accuracy',
    scoreCoherence: 'Coherence',
    scoreCitations: 'Citations',
    scoreOverall: 'Overall',
  },

  sourcesPanel: {
    sourcesTitle: 'Sources',
    openSourceTitle: 'Open source',
    fetchedPrefix: 'Fetched',
    citedAsPrefix: 'Cited as',
    reliability: {
      reliable: 'Reliable',
      moderate: 'Moderate',
      unverified: 'Unverified',
    },
  },

  history: {
    status: {
      pending: 'Pending',
      running: 'Running',
      completed: 'Completed',
      failed: 'Failed',
    },
    emptyTitle: 'No research runs yet',
    emptyDescription:
      'Start your first research query to see your runs appear here. Each run will be tracked with its status, iterations, and results.',
    startResearch: 'Start Research',
    deleteRunTitle: 'Delete Run',
    deleteRunSubtitle: 'This action cannot be undone',
    deleteRunPrompt:
      'Are you sure you want to delete this run? All associated data will be permanently removed.',
    cancel: 'Cancel',
    deleting: 'Deleting...',
    delete: 'Delete',
    loadFailed: 'Failed to load research history.',
    deleteFailed: 'Failed to delete run.',
    title: 'Research History',
    subtitle: 'Browse and revisit past research runs',
    filterPlaceholder: 'Filter by query...',
    refresh: 'Refresh',
    refreshTitle: 'Refresh',
    noRunsMatchPrefix: 'No runs match',
    deleteRunButtonTitle: 'Delete run',
    justNow: 'Just now',
  },

  projects: {
    title: 'Projects',
    subtitle: 'Organize your research into collections',
    heroTitle: 'Coming Soon',
    heroDescription:
      'Projects will let you organize research runs into named collections, making it easy to revisit related findings, share context across runs, and build a structured knowledge base.',
    underDevelopment: 'Under Development',
    ctaTitle: 'Start a new research run',
    ctaDescription:
      'Your runs will be automatically available for projects once launched.',
    ctaButton: 'New Research',
    features: [
      {
        title: 'Organize Research',
        description:
          'Group related runs into projects for easier navigation and context.',
      },
      {
        title: 'Tags & Labels',
        description:
          'Categorize projects with custom tags to quickly find what you need.',
      },
      {
        title: 'Project Insights',
        description:
          'Track research progress with aggregated metrics and timelines.',
      },
      {
        title: 'Version History',
        description: 'Track iterations and compare report versions over time.',
      },
      {
        title: 'Collaboration',
        description: 'Share projects and research with team members.',
      },
      {
        title: 'Knowledge Base',
        description:
          'Build a structured knowledge base from all your research.',
      },
    ],
  },

  settings: {
    defaultApiUrl: 'http://localhost:8000',
    defaultModel: 'auto',
    defaultDepth: 'standard',
    modelOptions: [
      { value: 'auto', label: 'Auto (recommended)' },
      { value: 'fast', label: 'Fast (llama-3.1-8b-instant)' },
      { value: 'expert', label: 'Expert (llama-3.1-70b-versatile)' },
    ],
    depthOptions: [
      { value: 'quick', label: 'Quick', description: 'Fast overview' },
      { value: 'standard', label: 'Standard', description: 'Balanced depth' },
      { value: 'deep', label: 'Deep', description: 'Thorough research' },
    ],
    toastSaved: 'Settings saved successfully',
    toastReset: 'Settings reset to defaults',
    title: 'Settings',
    subtitle: 'Configure your research agent preferences',
    reset: 'Reset',
    save: 'Save Settings',
    sections: {
      apiTitle: 'API Configuration',
      apiDesc: 'Backend connection settings',
      appearanceTitle: 'Appearance',
      appearanceDesc: 'Choose the UI theme',
      modelTitle: 'Model Preferences',
      modelDesc: 'Default model and research depth',
    },
    apiBaseUrl: 'API Base URL',
    apiHelp: 'The URL where your research agent API is running.',
    apiPlaceholder: 'http://localhost:8000',
    light: 'Light',
    dark: 'Dark',
    defaultModelLabel: 'Default Model',
    defaultModelHelp: 'Auto selects the best available model.',
    defaultDepthLabel: 'Default Research Depth',
    defaultDepthHelp: 'Controls how many iterations the agent performs.',
  },

  agentStateLabels: {
    intake: 'Understanding Prompt',
    plan: 'Planning',
    plan_complete: 'Planning Completed',
    query_generate: 'Generating Queries',
    queries_generated: 'Queries Ready',
    search: 'Searching',
    search_complete: 'Search Completed',
    fetch_parse: 'Fetching Pages',
    fetch_complete: 'Fetch Completed',
    index: 'Indexing',
    index_complete: 'Indexing Completed',
    retrieve: 'Retrieving Evidence',
    retrieve_complete: 'Evidence Ready',
    synthesize: 'Writing Response',
    synthesize_complete: 'Draft Completed',
    evaluate: 'Evaluating',
    evaluate_complete: 'Evaluation Completed',
    refine: 'Refining',
    refine_complete: 'Refinement Completed',
    max_iterations_reached: 'Iteration Limit Reached',
    finalize: 'Completed',
    failed: 'Failed',
    error: 'Error',
    research_gate: 'Classifying Query',
    prompt_guard: 'Safety Check',
    complexity_scored: 'Scoring Complexity',
    evidence_packed: 'Packing Evidence',
    verification_started: 'Verifying',
    verification_complete: 'Verification Done',
    pdf_generated: 'PDF Ready',
    steering_queued: 'Steering Queued',
    steering_applied: 'Steering Applied',
  } as Record<string, string>,
} as const;
