"""PDF Generator – converts Markdown reports to PDF files.

Uses markdown → HTML → PDF pipeline.
Preserves headings, bullets, citations, clickable URLs.
"""

from __future__ import annotations

import logging
import re
from io import BytesIO
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_REPORTS_DIR = Path(__file__).parent.parent.parent / "reports"


def _ensure_reports_dir() -> Path:
    _REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    return _REPORTS_DIR


def _md_to_html(md_text: str) -> str:
    """Convert Markdown to HTML with basic formatting."""
    html = md_text

    # Headers
    html = re.sub(r"^#### (.+)$", r"<h4>\1</h4>", html, flags=re.MULTILINE)
    html = re.sub(r"^### (.+)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
    html = re.sub(r"^## (.+)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
    html = re.sub(r"^# (.+)$", r"<h1>\1</h1>", html, flags=re.MULTILINE)

    # Bold and italic
    html = re.sub(r"\*\*\*(.+?)\*\*\*", r"<strong><em>\1</em></strong>", html)
    html = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", html)
    html = re.sub(r"\*(.+?)\*", r"<em>\1</em>", html)

    # Links
    html = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', html)

    # Inline code
    html = re.sub(r"`([^`]+)`", r"<code>\1</code>", html)

    # Bullet lists
    lines = html.split("\n")
    result: list[str] = []
    in_list = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                result.append("<ul>")
                in_list = True
            result.append(f"<li>{stripped[2:]}</li>")
        elif stripped.startswith(("1.", "2.", "3.", "4.", "5.", "6.", "7.", "8.", "9.")):
            if not in_list:
                result.append("<ol>")
                in_list = True
            text = re.sub(r"^\d+\.\s*", "", stripped)
            result.append(f"<li>{text}</li>")
        else:
            if in_list:
                result.append("</ul>" if result[-2].startswith("<ul") or any("<ul>" in r for r in result[-5:]) else "</ol>")
                in_list = False
            if stripped and not stripped.startswith("<h"):
                result.append(f"<p>{stripped}</p>")
            else:
                result.append(stripped)

    if in_list:
        result.append("</ul>")

    return "\n".join(result)


_PDF_CSS = """
body {
    font-family: 'Helvetica', 'Arial', sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #333;
    max-width: 700px;
    margin: 0 auto;
    padding: 40px 30px;
}
h1 { font-size: 22pt; color: #1a1a2e; margin-top: 30px; border-bottom: 2px solid #16213e; padding-bottom: 8px; }
h2 { font-size: 16pt; color: #16213e; margin-top: 24px; border-bottom: 1px solid #e0e0e0; padding-bottom: 5px; }
h3 { font-size: 13pt; color: #0f3460; margin-top: 18px; }
h4 { font-size: 11pt; color: #533483; margin-top: 14px; }
p { margin: 6px 0; text-align: justify; }
ul, ol { margin: 8px 0; padding-left: 24px; }
li { margin: 3px 0; }
a { color: #0066cc; text-decoration: underline; }
code { background: #f4f4f4; padding: 2px 5px; border-radius: 3px; font-size: 10pt; }
strong { color: #1a1a2e; }
.citation { color: #0066cc; font-weight: bold; }
.footer { margin-top: 40px; text-align: center; font-size: 9pt; color: #888; border-top: 1px solid #e0e0e0; padding-top: 10px; }
"""


def generate_pdf_from_markdown(
    report_md: str,
    run_id: str,
    title: str = "Research Report",
) -> Path | None:
    """Convert a Markdown report to PDF and save it.

    Returns the Path to the generated PDF, or None on failure.
    """
    reports_dir = _ensure_reports_dir()
    pdf_path = reports_dir / f"{run_id}.pdf"

    # Convert MD → HTML
    body_html = _md_to_html(report_md)

    full_html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>{_PDF_CSS}</style>
</head>
<body>
{body_html}
<div class="footer">
    Generated by Autonomous Research Agent | Run ID: {run_id}
</div>
</body>
</html>"""

    # Try WeasyPrint first, then fall back to basic HTML file
    try:
        from weasyprint import HTML
        HTML(string=full_html).write_pdf(str(pdf_path))
        logger.info("PDF generated with WeasyPrint: %s", pdf_path)
        return pdf_path
    except ImportError:
        logger.info("WeasyPrint not available, trying reportlab")
    except Exception as exc:
        logger.warning("WeasyPrint failed: %s, trying reportlab", exc)

    # Fallback: ReportLab
    try:
        return _generate_with_reportlab(report_md, run_id, pdf_path)
    except ImportError:
        logger.warning("reportlab not available either, saving as HTML")
    except Exception as exc:
        logger.warning("reportlab failed: %s, saving as HTML", exc)

    # Last resort: save as HTML
    html_path = reports_dir / f"{run_id}.html"
    html_path.write_text(full_html, encoding="utf-8")
    logger.info("Saved report as HTML: %s", html_path)
    return html_path


def _generate_with_reportlab(report_md: str, run_id: str, pdf_path: Path) -> Path:
    """Generate PDF using ReportLab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer

    doc = SimpleDocTemplate(str(pdf_path), pagesize=A4,
                            leftMargin=0.75*inch, rightMargin=0.75*inch,
                            topMargin=0.75*inch, bottomMargin=0.75*inch)

    styles = getSampleStyleSheet()

    # Custom styles
    styles.add(ParagraphStyle(
        "H1Custom", parent=styles["Heading1"], fontSize=18, spaceAfter=12,
    ))
    styles.add(ParagraphStyle(
        "H2Custom", parent=styles["Heading2"], fontSize=14, spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        "BodyCustom", parent=styles["Normal"], fontSize=10, spaceAfter=6,
        leading=14,
    ))

    elements: list[Any] = []
    lines = report_md.split("\n")

    for line in lines:
        stripped = line.strip()
        if not stripped:
            elements.append(Spacer(1, 6))
            continue

        # Clean for reportlab
        clean = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        clean = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", clean)
        clean = re.sub(r"\*(.+?)\*", r"<i>\1</i>", clean)
        clean = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2" color="blue">\1</a>', clean)

        if stripped.startswith("# "):
            elements.append(Paragraph(clean[2:], styles["H1Custom"]))
        elif stripped.startswith("## "):
            elements.append(Paragraph(clean[3:], styles["H2Custom"]))
        elif stripped.startswith("### "):
            elements.append(Paragraph(clean[4:], styles["Heading3"]))
        elif stripped.startswith("- ") or stripped.startswith("* "):
            elements.append(Paragraph(f"• {clean[2:]}", styles["BodyCustom"]))
        else:
            elements.append(Paragraph(clean, styles["BodyCustom"]))

    # Footer
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        f"<i>Generated by Autonomous Research Agent | Run ID: {run_id}</i>",
        styles["Normal"],
    ))

    doc.build(elements)
    logger.info("PDF generated with ReportLab: %s", pdf_path)
    return pdf_path


def get_pdf_path(run_id: str) -> Path | None:
    """Check if a PDF exists for a given run ID."""
    reports_dir = _ensure_reports_dir()
    pdf_path = reports_dir / f"{run_id}.pdf"
    if pdf_path.exists():
        return pdf_path
    html_path = reports_dir / f"{run_id}.html"
    if html_path.exists():
        return html_path
    return None
